const items = [
    { title: "Trapped Within", tag: ["mix"], img: "./assets/img1.jpg" },
    { title: "NTEG-Pro tools | Package Design", tag: ["design"], img: "./assets/img2.jpg" },
    { title: "Heavens Above | Ian Matthew ft Zar Da Merc", tag: ["music"], img: "./assets/img3.jpg" },
    { title: "Luminous Whispers", tag: ["mix"], img: "./assets/img4.jpg" },
    { title: "My Royalties | Package Design", tag: ["design"], img: "./assets/img5.jpg" },
    { title: "Into the Enchanted Realm", tag: ["mix"], img: "./assets/img6.jpg" },
    { title: "American Faith | Cap Design", tag: ["design"], img: "./assets/img7.jpg" },
    { title: "Graffiti Dreams | Album Art Design", tag: ["music"], img: "./assets/img8.jpg" },
    { title: "Framed Journey", tag: ["mix"], img: "./assets/img9.jpg" },
    { title: "By the river | Isabelle Anderson", tag: ["music"], img: "./assets/img10.jpg" },
    { title: "Hoodie Design | MasterPiece", tag: ["design"], img: "./assets/img11.jpg" },
    { title: "Puff & Chill", tag: ["mix"], img: "./assets/img12.jpg" },
    { title: "On This Wave | Kel Crimes", tag: ["music"], img: "./assets/img13.jpg" },
    { title: "Phantom of the Snow", tag: ["mix"], img: "./assets/img14.jpg" },
    { title: "T-Shirt Design | HNDE", tag: ["design"], img: "./assets/img15.jpg" },
    { title: "Mamba’s Final Walk", tag: ["mix"], img: "./assets/img16.jpg" },
    { title: "Dreamscape Gazing", tag: ["mix"], img: "./assets/img17.jpg" },
    { title: "Bluegrass Uke | Album Art", tag: ["music"], img: "./assets/img18.jpg" },
    { title: "Sports Bra Design | Three Kings", tag: ["design"], img: "./assets/img19.jpg" },
    { title: "Galactic Slapshot", tag: ["mix"], img: "./assets/img20.jpg" },
    { title: "Men's Heat Gear Long Sleeve | Three Kings", tag: ["design"], img: "./assets/img21.jpg" },
    { title: "FUN | Aria Elan", tag: ["music"], img: "./assets/img22.jpg" },
    { title: "Castle of the Forsaken", tag: ["mix"], img: "./assets/img23.jpg" },
    { title: "Unisex Drawstrings Lightweight Bag | Three Kings", tag: ["design"], img: "./assets/img24.jpg" },
    // { title: "Aurora's Whisper", tag: ["mix"], img: "./assets/img25.jpg" },
    { title: "Hoodie Design | MasterPiece", tag: ["design"], img: "./assets/img26.jpg" },
    { title: "Musick | Youtube Cover", tag: ["music"], img: "./assets/img27.jpg" },
    { title: "Gaze Beyond the Storm | Mikey Hamptons", tag: ["music"], img: "./assets/img28.jpg" },
    { title: "Red Cap Design | Three Kings", tag: ["design"], img: "./assets/img29.jpg" },
    { title: "The Essence of Eden | Album Art", tag: ["music"], img: "./assets/img30.jpg" },
    // { title: "Mystical Frequencies", tag: ["mix"], img: "./assets/img31.jpg" },
    // { title: "Serenity in Chaos", tag: ["mix"], img: "./assets/img32.jpg" },
    { title: "Love You Harder | Love Harder", tag: ["music"], img: "./assets/img33.jpg" },
    { title: "Black Shirt Design | HNDE", tag: ["design"], img: "./assets/img34.jpg" },
];
